
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@144", position = "1920x0", scale = 1 })
hl.monitor({ output = "HDMI-A-2", mode = "1920x1080@75", position = "0x0", scale = 1 })
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1", persistent = true})
hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-1", persistent = true})

hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-2", persistent = true})
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-2", persistent = true})
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-2", persistent = true})
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-2", persistent = true})
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-2", persistent = true})